version: "3.7"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        container_name: node-queue-api
        entrypoint: sh -c "npm ci && npm run dev"
        volumes:
            - ./:/home/node/app
        ports:
            - 3333:3333
        networks:
            - node-queue-net
        depends_on:
            - redis

    redis:
        image: bitnami/redis:7.2.4
        container_name: node-queue-redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - node-queue-redis-data:/bitnami/redis/data
        networks:
            - node-queue-net

    mailpit:
        image: axllent/mailpit
        container_name: node-queue-mailpit
        environment:
            MP_DATA_FILE: /data/mailpit.db
            MP_UI_BIND_ADDR: 0.0.0.0:8025
            MP_SMTP_AUTH_ACCEPT_ANY: "true"
            MP_SMTP_AUTH_ALLOW_INSECURE: "true"
            TZ: America/Sao_Paulo
        ports:
            - 8025:8025
        volumes:
            - node-queue-mail-data:/data
        networks:
            - node-queue-net

volumes:
    node-queue-redis-data:
    node-queue-mail-data:

networks:
    node-queue-net:
        driver: bridge
